<?php
?>

<script type="text/javascript">
    //<![CDATA[
    function generateRule() {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method:     'get',
            onSuccess: function(transport){
            
            if (transport.responseText){
                alert('The rule '+transport.responseText+' was created.');
            }
            else {
                alert('Error: The server didnt respond the id of the new rule');
            }
            }
        });
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>
